//! A favicon for every app, made from its icon, and for toolsite itself.
//!
//! Browsers look for `/favicon.ico` at the domain root unless a page links
//! one, and every app lives under `/p/<app>/`, so without help every tab on
//! the site would show the same blank square. Toolsite serves
//! `/p/<app>/favicon.svg`, `favicon.ico` and `apple-touch-icon.png` from the
//! app's icon whenever the bundle does not ship a file of that name, and adds
//! the links to an app's HTML when the page names no icon of its own.
//!
//! The icon comes in four shapes and each is drawn the same way the index
//! draws it: an uploaded image (resized), an inline SVG (re-written through
//! usvg, which keeps no script, no event attribute and no outside reference),
//! an emoji, or the generated badge of initials on the app's hue. Raster
//! sizes are drawn with resvg using a small font bundled in the binary, so
//! the container needs no fonts. There is no emoji font in it, so a raster
//! of an emoji icon falls back to the badge; the SVG keeps the emoji, which
//! is what current browsers show in a tab.

use crate::{
    config::Config,
    content::store::{self, Icon},
};
use base64::{engine::general_purpose::STANDARD as BASE64, Engine as _};
use std::{
    collections::HashMap,
    io::Cursor,
    path::PathBuf,
    sync::{Arc, LazyLock, Mutex},
    time::SystemTime,
};

/// Names toolsite answers for under an app when the bundle has no such file.
pub(crate) const NAMES: [&str; 3] = ["favicon.svg", "favicon.ico", "apple-touch-icon.png"];

/// Drawn into the badge, and nothing else. A subset of Liberation Sans Bold,
/// renamed as its licence asks; see assets/fonts/OFL.txt.
const FONT: &[u8] = include_bytes!("../../assets/fonts/ToolsiteInitials-Bold.ttf");
const FONT_FAMILY: &str = "Toolsite Initials";

const TOUCH_SIZE: u32 = 180;
const ICO_SIZES: [u32; 2] = [16, 32];

/// What an icon is, read once from disk.
enum Source {
    Raster(Vec<u8>),
    Svg(String),
    Emoji(String),
    Badge { initials: String, hue: u16 },
}

/// Generated bytes, kept until the icon or the page they came from changes.
type Key = (PathBuf, String, &'static str);
type Cache = HashMap<Key, (Stamp, Arc<Vec<u8>>)>;
static CACHE: LazyLock<Mutex<Cache>> = LazyLock::new(|| Mutex::new(HashMap::new()));

/// When the inputs last changed: the icon file and the page (whose title
/// makes the badge).
type Stamp = (Option<SystemTime>, Option<SystemTime>);

async fn modified(path: Option<PathBuf>) -> Option<SystemTime> {
    let path = path?;
    tokio::fs::metadata(path).await.ok()?.modified().ok()
}

/// The favicon `name` for `app`, with its media type. Nothing when `name` is
/// not one toolsite makes or the app does not exist.
pub(crate) async fn for_app(config: &Config, app: &str, name: &str) -> Option<(&'static str, Arc<Vec<u8>>)> {
    let name = NAMES.iter().copied().find(|n| *n == name)?;
    let page = store::page_path(config, app).await?;
    let icon = store::icon_path(config, app).await;
    let stamp = (modified(icon.clone()).await, modified(Some(page)).await);
    let key = (config.data_dir.clone(), app.to_string(), name);
    if let Some((cached, bytes)) = CACHE.lock().unwrap().get(&key)
        && *cached == stamp
    {
        return Some((media_type(name), bytes.clone()));
    }
    let source = read_source(config, app, icon).await;
    let bytes = tokio::task::spawn_blocking(move || draw(name, &source)).await.ok()?;
    let bytes = Arc::new(bytes);
    CACHE.lock().unwrap().insert(key, (stamp, bytes.clone()));
    Some((media_type(name), bytes))
}

fn media_type(name: &str) -> &'static str {
    match name {
        "favicon.svg" => "image/svg+xml",
        "favicon.ico" => "image/x-icon",
        _ => "image/png",
    }
}

async fn read_source(config: &Config, app: &str, icon: Option<PathBuf>) -> Source {
    let badge = || async {
        match store::generated_icon(config, app).await {
            Icon::Generated(initials, hue) => Source::Badge { initials, hue },
            _ => Source::Badge { initials: "?".into(), hue: store::slug_hue(app) },
        }
    };
    let Some(path) = icon else { return badge().await };
    let Ok(bytes) = tokio::fs::read(&path).await else { return badge().await };
    match classify(&bytes) {
        Some(source) => source,
        None => badge().await,
    }
}

/// Reads the shape of an icon file, the same rules `store::page_icon` uses.
fn classify(bytes: &[u8]) -> Option<Source> {
    if let Ok(text) = std::str::from_utf8(bytes) {
        let text = text.trim();
        if let Some(rest) = text.strip_prefix("data:") {
            let (head, data) = rest.split_once(',')?;
            let payload = if head.ends_with(";base64") {
                BASE64.decode(data.trim()).ok()?
            } else {
                urlencoding::decode(data).ok()?.into_owned().into_bytes()
            };
            return if head.starts_with("image/svg") {
                Some(Source::Svg(String::from_utf8(payload).ok()?))
            } else {
                Some(Source::Raster(payload))
            };
        }
        if text.starts_with('<') && text.contains("<svg") {
            return Some(Source::Svg(text.to_string()));
        }
        if !text.is_empty() && !text.starts_with('<') && text.chars().count() <= 4 {
            return Some(Source::Emoji(text.to_string()));
        }
    }
    (!bytes.is_empty()).then(|| Source::Raster(bytes.to_vec()))
}

fn draw(name: &str, source: &Source) -> Vec<u8> {
    match name {
        "favicon.svg" => svg_for(source).into_bytes(),
        "favicon.ico" => {
            let pngs: Vec<(u32, Vec<u8>)> =
                ICO_SIZES.iter().map(|&size| (size, png_for(source, size))).collect();
            ico(&pngs)
        }
        _ => png_for(source, TOUCH_SIZE),
    }
}

// --- SVG ----------------------------------------------------------------

fn escape(text: &str) -> String {
    text.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;")
}

/// The badge as the index draws it: initials on the app's hue, white.
pub(crate) fn badge_svg(initials: &str, background: &str) -> String {
    let size = if initials.chars().count() > 1 { 28 } else { 36 };
    format!(
        r##"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="{background}"/><text x="32" y="32" dy="0.35em" text-anchor="middle" font-family="{FONT_FAMILY}, system-ui, sans-serif" font-weight="700" font-size="{size}" fill="#ffffff">{}</text></svg>"##,
        escape(initials)
    )
}

/// `hsl(h 55% 45%)`, the index's badge colour, as hex so every renderer
/// reads it.
fn hue_hex(hue: u16) -> String {
    let (h, s, l) = (hue as f64, 0.55, 0.45);
    let c = (1.0 - (2.0 * l - 1.0f64).abs()) * s;
    let x = c * (1.0 - ((h / 60.0) % 2.0 - 1.0).abs());
    let m = l - c / 2.0;
    let (r, g, b) = match (h / 60.0) as u32 {
        0 => (c, x, 0.0),
        1 => (x, c, 0.0),
        2 => (0.0, c, x),
        3 => (0.0, x, c),
        4 => (x, 0.0, c),
        _ => (c, 0.0, x),
    };
    let to = |v: f64| ((v + m) * 255.0).round().clamp(0.0, 255.0) as u8;
    format!("#{:02x}{:02x}{:02x}", to(r), to(g), to(b))
}

fn emoji_svg(emoji: &str) -> String {
    format!(
        r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><text x="32" y="32" dy="0.35em" text-anchor="middle" font-size="52">{}</text></svg>"#,
        escape(emoji)
    )
}

fn options() -> resvg::usvg::Options<'static> {
    let mut options = resvg::usvg::Options::default();
    options.fontdb_mut().load_font_data(FONT.to_vec());
    options.font_family = FONT_FAMILY.to_string();
    // An icon may name images by path or URL. None is followed: the file
    // system and the network are not the icon's to reach.
    options.image_href_resolver = resvg::usvg::ImageHrefResolver {
        resolve_data: resvg::usvg::ImageHrefResolver::default_data_resolver(),
        resolve_string: Box::new(|_, _| None),
    };
    options
}

/// An uploaded SVG, written back out by usvg: what comes out is shapes and
/// paths, so a script, an `onload` or an outside link in the upload does not
/// survive. Nothing when it does not parse.
fn clean_svg(svg: &str) -> Option<String> {
    let tree = resvg::usvg::Tree::from_str(svg, &options()).ok()?;
    Some(tree.to_string(&resvg::usvg::WriteOptions::default()))
}

fn svg_for(source: &Source) -> String {
    match source {
        Source::Svg(svg) => clean_svg(svg).unwrap_or_else(|| badge_svg("?", &hue_hex(0))),
        Source::Emoji(emoji) => emoji_svg(emoji),
        Source::Badge { initials, hue } => badge_svg(initials, &hue_hex(*hue)),
        Source::Raster(bytes) => match fit_png(bytes, 64) {
            Some(png) => format!(
                r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><image width="64" height="64" href="data:image/png;base64,{}"/></svg>"#,
                BASE64.encode(png)
            ),
            None => badge_svg("?", &hue_hex(0)),
        },
    }
}

// --- raster -------------------------------------------------------------

/// Renders an SVG to a square PNG of `size`, or nothing if it does not
/// parse or draws no pixel at all.
fn render(svg: &str, size: u32) -> Option<Vec<u8>> {
    let tree = resvg::usvg::Tree::from_str(svg, &options()).ok()?;
    let mut pixmap = resvg::tiny_skia::Pixmap::new(size, size)?;
    let view = tree.size();
    let scale = (size as f32 / view.width()).min(size as f32 / view.height());
    resvg::render(&tree, resvg::tiny_skia::Transform::from_scale(scale, scale), &mut pixmap.as_mut());
    if pixmap.pixels().iter().all(|p| p.alpha() == 0) {
        return None;
    }
    pixmap.encode_png().ok()
}

/// An uploaded image, scaled to fit a transparent square of `size`.
fn fit_png(bytes: &[u8], size: u32) -> Option<Vec<u8>> {
    let image = image::load_from_memory(bytes).ok()?;
    let scaled = image.resize(size, size, image::imageops::FilterType::Lanczos3).to_rgba8();
    let mut canvas = image::RgbaImage::new(size, size);
    let (x, y) = ((size - scaled.width()) / 2, (size - scaled.height()) / 2);
    image::imageops::overlay(&mut canvas, &scaled, x as i64, y as i64);
    let mut out = Cursor::new(Vec::new());
    canvas.write_to(&mut out, image::ImageFormat::Png).ok()?;
    Some(out.into_inner())
}

fn png_for(source: &Source, size: u32) -> Vec<u8> {
    let drawn = match source {
        Source::Raster(bytes) => fit_png(bytes, size),
        Source::Svg(svg) => render(svg, size),
        Source::Emoji(emoji) => render(&emoji_svg(emoji), size),
        Source::Badge { initials, hue } => render(&badge_svg(initials, &hue_hex(*hue)), size),
    };
    drawn
        .or_else(|| match source {
            // No emoji font here, or an image that would not decode: the
            // badge is better than a blank square.
            Source::Badge { .. } => None,
            _ => render(&badge_svg("?", &hue_hex(0)), size),
        })
        .unwrap_or_default()
}

/// An ICO holding PNG images, which every browser since 2010 reads.
fn ico(images: &[(u32, Vec<u8>)]) -> Vec<u8> {
    let count = images.len() as u16;
    let mut out = Vec::new();
    out.extend_from_slice(&[0, 0, 1, 0]);
    out.extend_from_slice(&count.to_le_bytes());
    let mut offset = 6 + 16 * images.len() as u32;
    for (size, png) in images {
        let side = if *size >= 256 { 0 } else { *size as u8 };
        out.extend_from_slice(&[side, side, 0, 0]);
        out.extend_from_slice(&1u16.to_le_bytes());
        out.extend_from_slice(&32u16.to_le_bytes());
        out.extend_from_slice(&(png.len() as u32).to_le_bytes());
        out.extend_from_slice(&offset.to_le_bytes());
        offset += png.len() as u32;
    }
    for (_, png) in images {
        out.extend_from_slice(png);
    }
    out
}

// --- toolsite's own -----------------------------------------------------

/// The sidebar's mark: a lowercase t on the primary colour.
pub(crate) fn site_svg() -> String {
    badge_svg("t", "#18181b").replace(r#"font-size="36""#, r#"font-size="40""#)
}

pub(crate) fn site_ico() -> Vec<u8> {
    let svg = site_svg();
    let pngs: Vec<(u32, Vec<u8>)> = ICO_SIZES
        .iter()
        .map(|&size| (size, render(&svg, size).unwrap_or_default()))
        .collect();
    ico(&pngs)
}

// --- the links ----------------------------------------------------------

/// How much of a document is looked at for its `<head>`. A page whose head
/// starts later than this is left alone rather than read whole.
const WINDOW: usize = 8 * 1024;

fn find(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack.windows(needle.len()).position(|w| w == needle)
}

/// Adds the favicon links to an app's HTML when its head names no icon.
///
/// This is the one place toolsite edits a published page. It is done
/// because browsers otherwise fetch `/favicon.ico` from the domain root,
/// which is toolsite's and not the app's, so every app would wear the same
/// icon. A page that declares any icon of its own is returned untouched, and
/// only the first few kilobytes are read, so a large page costs nothing.
pub(crate) fn with_links(app: &str, html: &[u8]) -> Option<Vec<u8>> {
    let window = &html[..html.len().min(WINDOW)];
    let lower: Vec<u8> = window.iter().map(|b| b.to_ascii_lowercase()).collect();
    let mut from = 0;
    let head = loop {
        let at = from + find(&lower[from..], b"<head")?;
        // `<head>` or `<head attr>`, never `<header>`.
        match lower.get(at + 5) {
            Some(b'>') | Some(b' ') | Some(b'\t') | Some(b'\n') | Some(b'\r') => break at,
            _ => from = at + 5,
        }
    };
    let open_end = head + find(&lower[head..], b">")? + 1;
    let close = find(&lower[open_end..], b"</head").map_or(lower.len(), |i| open_end + i);
    let region = &lower[open_end..close];
    let mut scan = 0;
    while let Some(i) = find(&region[scan..], b"<link") {
        let start = scan + i;
        let end = find(&region[start..], b">").map_or(region.len(), |j| start + j);
        let tag = &region[start..end];
        if find(tag, b"rel").is_some() && find(tag, b"icon").is_some() {
            return None;
        }
        scan = end;
    }
    let links = format!(
        r#"<link rel="icon" href="/p/{app}/favicon.svg" type="image/svg+xml"><link rel="alternate icon" href="/p/{app}/favicon.ico"><link rel="apple-touch-icon" href="/p/{app}/apple-touch-icon.png">"#
    );
    let mut out = Vec::with_capacity(html.len() + links.len());
    out.extend_from_slice(&html[..open_end]);
    out.extend_from_slice(links.as_bytes());
    out.extend_from_slice(&html[open_end..]);
    Some(out)
}

/// `with_links` for a string, returning the original when nothing is added.
pub(crate) fn add_links(app: &str, html: String) -> String {
    match with_links(app, html.as_bytes()) {
        Some(bytes) => String::from_utf8(bytes).unwrap_or(html),
        None => html,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_page_without_an_icon_link_gets_three_after_head() {
        let out = add_links("crm", "<!doctype html><html><HEAD lang=x><title>x</title></HEAD><body></body></html>".into());
        let head_end = out.find("<HEAD lang=x>").unwrap() + "<HEAD lang=x>".len();
        assert!(out[head_end..].starts_with(r#"<link rel="icon" href="/p/crm/favicon.svg""#), "{out}");
        assert!(out.contains("/p/crm/favicon.ico") && out.contains("/p/crm/apple-touch-icon.png"));
    }

    #[test]
    fn a_page_that_names_its_own_icon_is_left_alone() {
        for html in [
            r#"<html><head><link rel="icon" href="x.png"></head></html>"#,
            r#"<html><head><link href="x.ico" rel="shortcut icon"></head></html>"#,
            r#"<html><head><LINK REL="apple-touch-icon" href="t.png"></head></html>"#,
        ] {
            assert_eq!(add_links("a", html.to_string()), html);
        }
    }

    #[test]
    fn a_header_element_is_not_a_head_and_no_head_means_no_change() {
        let html = "<html><body><header>x</header></body></html>";
        assert_eq!(add_links("a", html.to_string()), html);
        let fragment = "<p>just a fragment</p>";
        assert_eq!(add_links("a", fragment.to_string()), fragment);
    }

    #[test]
    fn an_uploaded_svg_loses_its_script_and_handlers() {
        let svg = r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10" onload="alert(1)"><script>alert(2)</script><rect width="10" height="10" fill="red"/><image href="file:///etc/passwd" width="10" height="10"/></svg>"#;
        let clean = clean_svg(svg).unwrap();
        assert!(!clean.contains("script") && !clean.contains("onload") && !clean.contains("passwd"), "{clean}");
        assert!(clean.contains("<path") || clean.contains("<rect"), "{clean}");
    }

    #[test]
    fn the_badge_renders_with_the_bundled_font() {
        let png = render(&badge_svg("QR", &hue_hex(200)), 32).expect("no pixels");
        let image = image::load_from_memory(&png).unwrap().to_rgba8();
        assert_eq!(image.dimensions(), (32, 32));
        // White glyph pixels prove the font drew; the badge alone has none.
        assert!(image.pixels().any(|p| p[0] > 230 && p[1] > 230 && p[2] > 230 && p[3] > 200));
    }

    #[test]
    fn an_emoji_falls_back_to_a_badge_in_raster_but_stays_an_emoji_in_svg() {
        let source = Source::Emoji("🐔".into());
        assert!(svg_for(&source).contains("🐔"));
        let png = png_for(&source, 32);
        assert!(!png.is_empty(), "the raster came out empty");
    }

    #[test]
    fn an_ico_lists_each_size_with_a_png_inside() {
        let source = Source::Badge { initials: "AB".into(), hue: 10 };
        let pngs: Vec<(u32, Vec<u8>)> = ICO_SIZES.iter().map(|&s| (s, png_for(&source, s))).collect();
        let bytes = ico(&pngs);
        assert_eq!(&bytes[..4], &[0, 0, 1, 0]);
        assert_eq!(u16::from_le_bytes([bytes[4], bytes[5]]), 2);
        assert_eq!(bytes[6], 16);
        assert_eq!(bytes[22], 32);
        let offset = u32::from_le_bytes(bytes[18..22].try_into().unwrap()) as usize;
        assert_eq!(&bytes[offset..offset + 8], b"\x89PNG\r\n\x1a\n");
    }

    #[test]
    fn the_hue_matches_css_hsl() {
        // hsl(0 55% 45%) is rgb(178, 52, 52).
        assert_eq!(hue_hex(0), "#b23434");
    }
}
